version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: vector-postgres
    environment:
      POSTGRES_DB: vector_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Riccardo2001
    ports:
      - '5433:5432'
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgvector_data:
