spring:
  application:
    name: deepseek-demo

  ai:
    ollama:
      chat:
        model: deepseek-r1:1.5b
      embedding:
        options:
          model: nomic-embed-text

    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW

  datasource:
    url: jdbc:postgresql://localhost:5432/ai-memory
    username: postgres
    password: Riccardo2001
    driver-class-name: org.postgresql.Driver

#http://localhost:8080